
" vim-plug plugins
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'tpope/vim-surround'
Plug 'derekwyatt/vim-scala'
Plug 'tpope/vim-fugitive'
Plug 'majutsushi/tagbar'
Plug 'rust-lang/rust.vim'
Plug 'altercation/vim-colors-solarized'

call plug#end()

" Plugin config

let g:formatter_yapf_style = 'pep8'
let g:airline_powerline_fonts = 1

map <C-z> :NERDTreeToggle<CR>
nmap <leader>t :TagbarToggle<CR>
" CTRL-p for file search
nmap <C-p> :FZF<CR>
" CTRL-l to clear highlighting
nnoremap <silent> <C-l> :nohl<CR><C-l>
" CTRL-b to make in current directory
nmap <C-B> :!make<CR>

" Other

set ls=2
set tags=~/tags
let mapleader = ','
set encoding=utf-8
set nu
set binary
set term=xterm-256color
colorscheme solarized
set bg=dark
set showcmd
set foldenable
set foldmethod=indent
set foldlevelstart=99
set autoindent
set clipboard=unnamed
set softtabstop=2
set shiftwidth=2
set expandtab
set mouse=a
syntax on
set history=1000
set undolevels=1000
set backspace=indent,eol,start
set ruler
set showmatch
set matchtime=3
set wildmenu
set wildmode=list:longest,full
set wildignore=*.swp,*.bak,*.pyc,*.class,*.a,*.o,*.aux,*.out
set showbreak=>
set hlsearch
set ignorecase
set smartcase
set hidden
set switchbuf=useopen
set scrolljump=5
set scrolloff=3

" Navigate between words (+ whitespace) using Tab and Back-slash
nnoremap <Tab> W
vnoremap <Tab> W
nnoremap \ B
vnoremap \ B

" Check spelling in text, LaTeX, and Markdown files.
autocmd BufReadPre *.txt setlocal spell
autocmd BufReadPre *.tex setlocal spell
autocmd BufReadPre *.md setlocal spell
