"
" Shoumik's .vimrc file
" Last Modified: 6/14/2020
"

" vim-plug plugins
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'tpope/vim-surround'
Plug 'derekwyatt/vim-scala'
Plug 'tpope/vim-fugitive'
Plug 'majutsushi/tagbar'
Plug 'rust-lang/rust.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'derekwyatt/vim-fswitch'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

" Set Leader to ','
let mapleader = ','

let $FZF_DEFAULT_COMMAND = 'rg --files --hidden'

" Custom Mappings
map <C-z> :NERDTreeToggle<CR>
nmap <C-p> :FZF<CR>
" Clear highlighting
nnoremap <silent> <C-l> :nohl<CR><C-l>
nmap <C-B> :!make<CR>
nmap <silent> <Leader>t :TagbarToggle<CR>
nmap <silent> <Leader>of :FSHere<cr>
nmap <silent> <Leader>sf :FSSplitRight<cr>

" Powerline status bar
let g:airline_powerline_fonts = 1

" FSSwitch Setup
au! BufEnter *c,*.cc,*cpp let b:fswitchdst = 'h,hh'
au! BufEnter *.h let b:fswitchdst = 'cc,c,cpp'
let fsnonewfiles=0

" C++ Highlighting
let g:cpp_no_function_highlight = 1
let g:cpp_posix_standard = 1

" Other
syntax on
set tags=tags
set ls=2
set wildmode=longest,list,full
set wildmenu
set encoding=utf-8
set nu
set binary
set term=xterm-256color
colorscheme solarized
set bg=dark
set showcmd
set foldenable
set foldmethod=indent
set foldlevelstart=99
set autoindent
set clipboard=unnamed
set softtabstop=2
set shiftwidth=2
set expandtab
set mouse=a
set history=1000
set colorcolumn=100
set textwidth=100
set undolevels=1000
set backspace=indent,eol,start
set ruler
set showmatch
set matchtime=3
set wildmenu
set wildmode=list:longest,full
set wildignore=*.swp,*.bak,*.pyc,*.class,*.a,*.o,*.aux,*.out,*.bin,*.jar
set showbreak=>
set hlsearch
set ignorecase
set smartcase
set hidden
set switchbuf=useopen
set scrolljump=5
set scrolloff=3

" Navigate between words (+ whitespace) using Tab and Back-slash
nnoremap <Tab> W
vnoremap <Tab> W
nnoremap \ B
vnoremap \ B

" Autowrapping for function-level comments.
autocmd Filetype c,cpp,cc,h,hh set comments^=:///

" Check spelling in text, LaTeX, and Markdown files.
autocmd BufReadPre *.txt setlocal spell
autocmd BufReadPre *.tex setlocal spell
autocmd BufReadPre *.md setlocal spell

" Trim trailing whitespace on write.
autocmd BufWritePre * %s/\s\+$//e
